# Generated by Django 2.1.2 on 2018-11-06 03:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdateContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=248)),
                ('last_name', models.CharField(blank=True, max_length=248, null=True)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=248, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=248, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=248, null=True)),
                ('facebook_key', models.CharField(blank=True, max_length=248, null=True)),
                ('twitter_key', models.CharField(blank=True, max_length=248, null=True)),
                ('linkedin_key', models.CharField(blank=True, max_length=248, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('reminders_enabled_manually', models.BooleanField(default=False)),
                ('reminders_disabled_manually', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Birthdate Contact',
                'verbose_name_plural': 'Birthdate Contacts',
            },
        ),
        migrations.CreateModel(
            name='BirthdateContactsSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_unique_template', models.BooleanField(default=False)),
                ('public_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('private_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=50)),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('remind_days_before', models.PositiveIntegerField(default=1)),
                ('contacts', models.ManyToManyField(to='birthdate.BirthdateContact')),
            ],
            options={
                'verbose_name': 'Birthdate Contacts Segment',
                'verbose_name_plural': 'Birthdate Contacts Segments',
            },
        ),
        migrations.CreateModel(
            name='BirthdateMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(default=None)),
                ('future_messages_scheuled', models.BooleanField(default=False)),
                ('reminders_scheduled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateTimeField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birthdate.BirthdateContact')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='BirthdateMessageReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_days_before', models.PositiveSmallIntegerField()),
                ('in_the_past', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('scheduled_for', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birthdate.BirthdateContact')),
            ],
            options={
                'verbose_name': 'Message Reminder',
                'verbose_name_plural': 'Message Reminders',
            },
        ),
        migrations.CreateModel(
            name='BirthdateMessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('subject', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('uses', models.PositiveIntegerField(default=0)),
                ('draft', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('has_been_cloned', models.BooleanField(default=False)),
                ('is_clone', models.BooleanField(default=False)),
                ('cloned_parent_key', models.CharField(blank=True, max_length=248, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Birthdate Message Template',
                'verbose_name_plural': 'Birthdate Message Templates',
            },
        ),
        migrations.CreateModel(
            name='BirthdateProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_key', models.CharField(blank=True, max_length=50, null=True)),
                ('message_credits', models.PositiveIntegerField(default=0)),
                ('has_unlimited_credits', models.BooleanField(default=False)),
                ('reminder_frequencies', models.CharField(default='[1, 5, 30]', max_length=248)),
            ],
            options={
                'verbose_name': 'Birthdate Profile',
                'verbose_name_plural': 'Birthdate Profiles',
            },
        ),
        migrations.AddField(
            model_name='birthdatemessagetemplate',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birthdate.BirthdateProfile'),
        ),
        migrations.AddField(
            model_name='birthdatemessage',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birthdate.BirthdateProfile'),
        ),
        migrations.AddField(
            model_name='birthdatemessage',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='birthdate.BirthdateMessageTemplate'),
        ),
        migrations.AddField(
            model_name='birthdatecontact',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birthdate.BirthdateProfile'),
        ),
    ]
