# Generated by Django 2.1.2 on 2018-11-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdatemessage',
            name='sent_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
