# Generated by Django 2.1.2 on 2018-11-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdate', '0002_auto_20181105_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdatemessage',
            name='scheduled_for',
            field=models.DateField(),
        ),
    ]
