# Generated by Django 2.1.2 on 2018-11-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdate', '0003_auto_20181105_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdateprofile',
            name='require_message_send_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
