# Generated by Django 2.1.5 on 2019-02-06 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthdate', '0004_birthdateprofile_require_message_send_confirmation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthdatecontact',
            options={'ordering': ['first_name', 'last_name', 'reminders_enabled'], 'verbose_name': 'Birthdate Contact', 'verbose_name_plural': 'Birthdate Contacts'},
        ),
        migrations.AlterModelOptions(
            name='birthdatemessage',
            options={'ordering': ['scheduled_for'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
