# Generated by Django 2.1.5 on 2019-02-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='parent_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
