# Generated by Django 2.1.5 on 2019-02-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_handling', '0002_auto_20190215_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='added_to_mailchimp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='host',
            field=models.CharField(choices=[('www', 'www'), ('birthdate', 'birthdate'), ('lunchmunch', 'lunchmunch'), ('tripweather', 'tripweather')], max_length=248),
        ),
    ]
