# Generated by Django 2.1.5 on 2019-02-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchmunch', '0002_auto_20190215_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='FD7640', editable=False, max_length=6),
        ),
    ]
