# Generated by Django 2.1.5 on 2019-02-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchmunch', '0003_auto_20190217_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='5AFE23', editable=False, max_length=6),
        ),
    ]
