# Generated by Django 2.1.5 on 2019-02-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchmunch', '0006_auto_20190219_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='B53FCA', editable=False, max_length=6),
        ),
    ]
