# Generated by Django 2.1.5 on 2019-02-06 00:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('start_loc', models.CharField(max_length=50)),
                ('end_loc', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 2, 6, 0, 55, 49, 108185, tzinfo=utc))),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
            },
        ),
    ]
