# Generated by Django 2.1.5 on 2019-02-15 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripweather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(default=datetime.date(2019, 2, 15)),
        ),
    ]
