# Generated by Django 2.1.5 on 2019-02-18 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripweather', '0002_auto_20190214_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(default=datetime.date(2019, 2, 18)),
        ),
    ]
